### ISSUE TITLE
The "make clean all" option is not working

### ISSUE THREAD

**Issue by rubyFeedback** [hoomanist/mish#2]
Doing this:

     make clean all 

on a fresh git clone checkout does not work.

make clean all
rm mish
rm: cannot remove 'mish': No such file or directory
make: *** [Makefile:17: clean] Error 1

Doing just "make":

mkdir built
clang -g  -c src/main.c -o built/main.o
make: clang: No such file or directory
make: *** [Makefile:8: all] Error 127

I was able to modify the makefile and replace clang with gcc and then make worked. But this is a bit cumbersome.

Could you also show how to install it in the main README.md via gcc instead? If this is supported?

**Comment by hoomanist** [comment]
it is going to compile well using gcc just change value of CC in Makefile :)
